name: 'Symlinks'
description: 'Create symlinks or shortcuts for self-hosted runners'
author: 'sb-ghvcs'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'file-plus'
  color: 'gray-dark'

# Define your inputs here.
inputs:
  source-path:
    description: 'The source path to create the symlink or shortcut for'
    required: true
  destination-path:
    description: 'The destination path to create the symlink or shortcut to'
    required: true
  override:
    description: 'Override whatever is at destination path if it exists'
    required: false
    default: false

# Define your outputs here.
outputs:
  source-path:
    description: 'Absolute path to the source of the symlink'
  output-path:
    description: 'Absolute path to the created symlink'

runs:
  using: node20
  main: dist/index.js
